(CONTAINER_EMPTY, 
 CONTAINER_CASSETTE, 
 CONTAINER_CALIB_CASSETTE, 
 CONTAINER_PUCK_ADAPTER,
 CONTAINER_UNKNOWN, 
 CONTAINER_NONE) = range(6)
 
(PORT_EMPTY, 
 PORT_GOOD, 
 PORT_UNKNOWN, 
 PORT_MOUNTED, 
 PORT_JAMMED,
 PORT_NONE) = range(6)

PORT_STATE_TABLE = {
    '0': PORT_EMPTY, 
    '1': PORT_GOOD, 
    'u': PORT_UNKNOWN , 
    'm': PORT_MOUNTED, 
    'j': PORT_JAMMED,
    '-': PORT_NONE }